# .github/workflows/deploy.yml

name: Build and Deploy Streamlit App to Azure

# ------------------------------------------------
# TRIGGER: When to run this workflow
# ------------------------------------------------
on:
  push:
    branches:
      - main # Deploys when you push to the 'main' branch
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# ------------------------------------------------
# JOBS: The sequence of tasks to run
# ------------------------------------------------
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu as the runner
    environment: production # Optional: for environment-specific secrets or rules

    steps:
      # 1. Checkout the repository code
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      # 2. Set up a specific Python version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # IMPORTANT: Change to your Python version if different

      # 3. Install Python dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Log in to Azure
      # Uses the Service Principal credential you will store in GitHub secrets
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 5. Deploy the app to Azure App Service
      - name: 'Deploy to Azure App Service'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }} # The name of your Azure App Service
          package: '.' # Deploy the entire repository
          startup-command: 'streamlit run streamlit_app.py' # IMPORTANT: Change 'app.py' to your main streamlit file
